version: "3"

services:
  mongo_service:
    image: mongo:latest
    container_name: docker-mongo
    ports:
     - 27019:27017
  hello-docker-react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-react-create-app
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node
    links:
      - mongo_service
